[package]

name = "racer"
version = "2.0.6"
license = "MIT"
description = "Code completion for Rust"
authors = ["Phil Dawes <phil@phildawes.net>"]
homepage = "https://github.com/phildawes/racer"
repository = "https://github.com/phildawes/racer"

[lib]
name = "racer"
path = "src/racer/lib.rs"

[[bin]]
name = "racer"
path = "src/bin/main.rs"
doc = false

[profile.release]
debug = true

[dependencies]
log = "~0.3.6"
syntex_syntax = "~0.52.0"
syntex_errors = "~0.52.0"
toml = "~0.2.1"
env_logger = "~0.3.4"
typed-arena = "~1.2.0"
clap = "~2.19.0"

[dependencies.clippy]
version = "0.0.103"
optional = true

[dev-dependencies]
rand = "0.3"
lazy_static = "0.2"

[features]
nightly = []
