[package]
name = "typed-arena"
version = "1.2.0"
authors = ["Simon Sapin <simon.sapin@exyr.org>"]
license = "MIT"
description = "The arena, a fast but limited type of allocator"
repository = "https://github.com/SimonSapin/rust-typed-arena"

[lib]
name = "typed_arena"
path = "src/lib.rs"
doctest = false
