language: rust
sudo: false

cache: cargo

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo test
  - cargo test --no-default-features --features hmac-openssl
