# bibtex
# Autogenerated from man page /usr/share/man/man1/bibtex.1.gz
# using Deroffing man parser
complete -c bibtex -o min-crossrefs --description 'option defines the minimum number of crossref r… [See Man Page]'
complete -c bibtex -o terse --description 'option,  operates silently.'

