# certtool
# Autogenerated from man page /usr/share/man/man1/certtool.1.gz
# using Deroffing man parser
complete -c certtool -l load-ca-certificate --description '$ certtool --load-ca-certificate ca.'

