# m4
# Autogenerated from man page /usr/share/man/man1/m4.1p.gz
# using Deroffing man parser
complete -c m4 -s D --description 'and.'
complete -c m4 -s U --description 'options shall be significant, and options can b… [See Man Page]'
complete -c m4 -s s --description 'Enable line synchronization output for the c99 … [See Man Page]'

