# make
# Autogenerated from man page /usr/share/man/man1/make.1p.gz
# using Deroffing man parser
complete -c make -s e --description 'Cause environment variables, including those wi… [See Man Page]'
complete -c make -s f --description 'Specify a different makefile.'
complete -c make -s i --description 'Ignore error codes returned by invoked commands.'
complete -c make -s k --description 'Continue to update other targets that do not de… [See Man Page]'
complete -c make -s n --description 'Write commands that would be executed on standa… [See Man Page]'
complete -c make -s p --description 'Write to standard output the complete set of ma… [See Man Page]'
complete -c make -s q --description 'Return a zero exit value if the target file is … [See Man Page]'
complete -c make -s r --description 'Clear the suffix list and do not use the built-in rules.'
complete -c make -s S --description 'Terminate make if an error occurs while executi… [See Man Page]'
complete -c make -s s --description 'Do not write makefile command lines or touch messages (see.'
complete -c make -s t --description 'to standard output before executing.'
complete -c make -s P --description 'to achieve the portable behavior.'
complete -c make -s d --description 'option to make is frequently used to produce de… [See Man Page]'

