# ofm2opl
# Autogenerated from man page /usr/share/man/man1/ofm2opl.1.gz
# using Deroffing man parser
complete -c ofm2opl -o charcode-format --description 'output character codes according to type, eithe… [See Man Page]'
complete -c ofm2opl -o char-format --description 'output character codes according to stype, eith… [See Man Page]'
complete -c ofm2opl -o 'charcode-format.' --description 'historical compatibility. ).'
complete -c ofm2opl -o num-format --description 'output numbers according to ntype, either `hex\'… [See Man Page]'
complete -c ofm2opl -o text-format --description 'output coding scheme and family according to tt… [See Man Page]'
complete -c ofm2opl -o help --description 'display a brief summary of syntax and options .'
complete -c ofm2opl -o verbose --description 'display progress reports.'
complete -c ofm2opl -o version --description 'output version information and exit.'

