# pdfopen
# Autogenerated from man page /usr/share/man/man1/pdfopen.1.gz
# using Deroffing man parser
complete -c pdfopen -s h -l help -s '?' --description 'output help and exit.'
complete -c pdfopen -s v -l version -s V --description 'output the version number and exit.'
complete -c pdfopen -s p -l page --description 'when starting the viewer, display page <n> of t… [See Man Page]'
complete -c pdfopen -s g -l goto --description 'when starting the viewer, display the page of t… [See Man Page]'
complete -c pdfopen -s r -l reset_focus --description 'after sending commands to the PDF viewer, attem… [See Man Page]'
complete -c pdfopen -o viewer -l viewer --description 'use (respectively) Adobe Reader 9 (in a new win… [See Man Page]'

