# profanity
# Autogenerated from man page /usr/share/man/man1/profanity.1.gz
# using Deroffing man parser
complete -c profanity -s v -l version --description 'Show version and build information.'
complete -c profanity -s h -l help --description 'Show help on command line arguments.'
complete -c profanity -s a -l account --description 'Auto connect to an account on startup,  ACCOUNT… [See Man Page]'
complete -c profanity -s l -l log --description 'Set the logging level, LEVEL may be set to DEBU… [See Man Page]'

