# texindy
# Autogenerated from man page /usr/share/man/man1/texindy.1.gz
# using Type1
complete -c texindy -l version -s V --description 'el.'
complete -c texindy -l help -s h -s '?' --description 'el.'
complete -c texindy -l quiet -s q --description 'el.'
complete -c texindy -l verbose -s v --description 'el.'
complete -c texindy -l debug -s d --description 'el.'
complete -c texindy -l out-file -s o --description 'el.'
complete -c texindy -l log-file -s t --description 'el.'
complete -c texindy -l language -s L --description 'el.'
complete -c texindy -l codepage -s C --description 'el.'
complete -c texindy -l module -s M --description 'el.'
complete -c texindy -l input-markup -s I --description 'el.'

