# xindy
# Autogenerated from man page /usr/share/man/man1/xindy.1.gz
# using Type1
complete -c xindy -l version -s V --description 'el.'
complete -c xindy -l help -s h -s '?' --description 'el.'
complete -c xindy -l quiet -s q --description 'el.'
complete -c xindy -l verbose -s v --description 'el.'
complete -c xindy -l debug -s d --description 'el.'
complete -c xindy -l out-file -s o --description 'el.'
complete -c xindy -l log-file -s t --description 'el.'
complete -c xindy -l language -s L --description 'el.'
complete -c xindy -l codepage -s C --description 'el.'
complete -c xindy -l module -s M --description 'el.'
complete -c xindy -l input-markup -s I --description 'el.'
complete -c xindy -l interactive --description 'el.'
complete -c xindy -l mem-file --description 'el.'

