[package]

name = "traitobject"
version = "0.0.3"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]
repository = "https://github.com/reem/rust-traitobject.git"
description = "Unsafe helpers for working with raw trait objects."
readme = "README.md"
license = "MIT"

